
# pull the python3.11 image
FROM python:3.11
 
# set the working directory in the container
WORKDIR /src/gold_app

# copy the requirements file into the container
COPY requirements.txt ./requirements.txt

# install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# copy the current directory contents into the container at /usr/src/app
COPY src/gold_app/ ./gold_app
COPY src/app.py ./app.py

COPY src/utils/ ./utils

# command to run on container start
CMD [ "python", "./app.py"]
