
name: Run the applicaiton

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight 

jobs:
  Run-the-applicaiton:
    name: Run applicaiton
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11] 

    steps:
    - uses: actions/checkout@v2
    
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the application
      run: |
        python app.py