
name: Run the applicaiton

on:
  workflow_dispatch:
  
  # https://crontab.guru/#0_19_*_*_*
  schedule:
    - cron: '0 19 * * *' # Run every day at 8 PM germany time 

jobs:
  Run-the-applicaiton:
    name: Run applicaiton
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11] 

    steps:

    - uses: actions/checkout@v2
    
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create config file
      run: echo "${{ secrets.GAPI_TOKEN }}" > token.json

    - name: Run the school messages app
      env:
        SCHOOL_ADDRESS_1: ${{ secrets.SCHOOL_ADDRESS_1 }}
        SCHOOL_ADDRESS_2: ${{ secrets.SCHOOL_ADDRESS_2 }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        app_mode: school_app
      run: |
        python src/app.py

    - name: Run the gold messages app
      env:
        BKP_TELEGRAM_TOKEN: ${{ secrets.BKP_TELEGRAM_TOKEN }}
        BKP_TELEGRAM_CHAT_ID: ${{ secrets.BKP_TELEGRAM_CHAT_ID }}
        app_mode: gold_app
      run: |
          python src/app.py