
name: Run the applicaiton

on:
  workflow_dispatch:
  
  # https://crontab.guru/#0_19_*_*_*
  schedule:
    - cron: '0 5 * * *' # Run every day at 6 AM germany time 

jobs:
  Run-the-applicaiton:
    name: Run applicaiton
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11] 

    steps:

    - uses: actions/checkout@v2
    
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Create .env_gold_app file
      run: |
        echo "BKP_TELEGRAM_TOKEN=${{ secrets.BKP_TELEGRAM_TOKEN }}" > .env_gold_app
        echo "BKP_TELEGRAM_CHAT_ID=${{ secrets.BKP_TELEGRAM_CHAT_ID }}" >> .env_gold_app
        echo "app_mode=gold_app" >> .env_gold_app


    - name: Create .env_school_app file
      run: |
        echo "SCHOOL_ADDRESS_1=${{ secrets.SCHOOL_ADDRESS_1 }}" > .env_school_app
        echo "SCHOOL_ADDRESS_2=${{ secrets.SCHOOL_ADDRESS_2 }}" >> .env_school_app
        echo "OPEN_AI_MODEL=${{ secrets.OPEN_AI_MODEL }}" >> .env_school_app
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env_school_app
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env_school_app
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env_school_app
        echo "app_mode=school_app" >> .env_school_app

    - name: Create .env_exp_track_app file
      run: |
        echo "OPEN_AI_MODEL=${{ secrets.OPEN_AI_MODEL }}" >> .env_exp_track_app
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env_exp_track_app
        echo "TELEGRAM_APP_ID=${{ secrets.TELEGRAM_APP_ID }}" >> .env_exp_track_app
        echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}" >> .env_exp_track_app
        echo "TELEGRAM_PHONE=${{ secrets.TELEGRAM_PHONE }}" >> .env_exp_track_app
        echo "app_mode=exp_tracking_app" >> .env_exp_track_app


    - name: Create config file
      run: echo "${{ secrets.GAPI_TOKEN }}" > token.json

    - name: Pull docker image
      run: docker pull anilkumarkanasani/messaging_app:latest

    # - name: Run docker container as school app
    #   run: docker run --name school_app --volume ./token.json:/src/token.json --env-file .env_school_app anilkumarkanasani/messaging_app:latest
    
    # - name: Run docker container as gold app
    #   run: docker run --name gold_app --env-file .env_gold_app anilkumarkanasani/messaging_app:latest

    - name: Create gsheet credential file
      env:
        GSHEET_CREDS_BASE64: ${{ secrets.GSHEET_CREDS_BASE64 }}
      run: |
        echo $GSHEET_CREDS_BASE64 | base64 --decode > gsheet_credentials.json

    - name: Create telegram session file
      env:
        ANIL_TELEGRAM_SESSION_BASE64: ${{ secrets.ANIL_TELEGRAM_SESSION_BASE64 }}
      run: |
        echo $ANIL_TELEGRAM_SESSION_BASE64 | base64 --decode > anil_telegram.session

    - name: Run docker container as exp track app
      run: docker run --name exp_track_app --volume ./gsheet_credentials.json:/src/gsheet_credentials.json --volume ./anil_telegram.session:/src/anil_telegram.session --env-file .env_exp_track_app anilkumarkanasani/messaging_app:latest